### ISSUE TITLE
Server error on sa_summary_pdf

### ISSUE THREAD

**Issue by ehmatthes** [openlearningtools/opencompetencies#120]
Again! May be an issue with a cached urls.py being used by one of the gunicorn workers. I'm not sure I stopped all the gunicorn workers before restarting.

**Comment by ehmatthes** [comment]
Killed all gunicorn workers, restarted gunicorn, seems to be working again.

**Comment by ehmatthes** [comment]
This is creeping up again. In the logs, I'm getting the following error:

    Internal Server Error: /sa_summary_pdf/2/
    Traceback (most recent call last):
      File "/srv/projects/opencompetencies/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/srv/projects/opencompetencies/competencies/views.py", line 82, in sa_summary_pdf
        print('Generating pdf of sa_summary...')
    OSError: [Errno 5] Input/output error

I found this [SO post](http://stackoverflow.com/questions/10409897/ioerror-input-output-error-when-printing), which might be relevant.

I'm going to try restarting gunicorn, see if that fixes the error. Then close the terminal in which I started gunicorn, and see if the fix is persistent.

**Comment by ehmatthes** [comment]
Closing in favor of the more specific #122.
