### ISSUE TITLE
PDF not generated when remote terminal session closed

### ISSUE THREAD

**Issue by ehmatthes** [openlearningtools/opencompetencies#122]
After uploading the code to generate pdfs of sa_summary, and restarting gunicorn, pdf generation works as long as the terminal is open. Closing the connection to the remote server causes a server error, with the following output in the logs:

    Internal Server Error: /sa_summary_pdf/2/
    Traceback (most recent call last):
      File "/srv/projects/opencompetencies/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/srv/projects/opencompetencies/competencies/views.py", line 82, in sa_summary_pdf
        print('Generating pdf of sa_summary...')
    OSError: [Errno 5] Input/output error

This is a more specific reticketing of #120.

**Comment by ehmatthes** [comment]
Try:
- [ ] Removing print() statements from sa_summary_pdf.py.
- [ ] starting gunicorn with an explicit terminal command, not an alias. (Maybe it's not fully a background process detached from the terminal?

**Comment by ehmatthes** [comment]
I've read that reportlab is not thread safe, which may play into this.

**Comment by ehmatthes** [comment]
Closing for now, hopeful this is really fixed.
